# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.12.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.12.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/benoitc/BarrelProject/erlang-rocksdb

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/benoitc/BarrelProject/erlang-rocksdb

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.12.4/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.12.4/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/benoitc/BarrelProject/erlang-rocksdb/CMakeFiles /Users/benoitc/BarrelProject/erlang-rocksdb/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/benoitc/BarrelProject/erlang-rocksdb/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rocksdb.so

# Build rule for target.
rocksdb.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rocksdb.so
.PHONY : rocksdb.so

# fast build rule for target.
rocksdb.so/fast:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/build
.PHONY : rocksdb.so/fast

#=============================================================================
# Target rules for targets named rocksdb

# Build rule for target.
rocksdb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rocksdb
.PHONY : rocksdb

# fast build rule for target.
rocksdb/fast:
	$(MAKE) -f CMakeFiles/rocksdb.dir/build.make CMakeFiles/rocksdb.dir/build
.PHONY : rocksdb/fast

c_src/backup.o: c_src/backup.cc.o

.PHONY : c_src/backup.o

# target to build an object file
c_src/backup.cc.o:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/backup.cc.o
.PHONY : c_src/backup.cc.o

c_src/backup.i: c_src/backup.cc.i

.PHONY : c_src/backup.i

# target to preprocess a source file
c_src/backup.cc.i:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/backup.cc.i
.PHONY : c_src/backup.cc.i

c_src/backup.s: c_src/backup.cc.s

.PHONY : c_src/backup.s

# target to generate assembly for a file
c_src/backup.cc.s:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/backup.cc.s
.PHONY : c_src/backup.cc.s

c_src/batch.o: c_src/batch.cc.o

.PHONY : c_src/batch.o

# target to build an object file
c_src/batch.cc.o:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/batch.cc.o
.PHONY : c_src/batch.cc.o

c_src/batch.i: c_src/batch.cc.i

.PHONY : c_src/batch.i

# target to preprocess a source file
c_src/batch.cc.i:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/batch.cc.i
.PHONY : c_src/batch.cc.i

c_src/batch.s: c_src/batch.cc.s

.PHONY : c_src/batch.s

# target to generate assembly for a file
c_src/batch.cc.s:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/batch.cc.s
.PHONY : c_src/batch.cc.s

c_src/bitset_merge_operator.o: c_src/bitset_merge_operator.cc.o

.PHONY : c_src/bitset_merge_operator.o

# target to build an object file
c_src/bitset_merge_operator.cc.o:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/bitset_merge_operator.cc.o
.PHONY : c_src/bitset_merge_operator.cc.o

c_src/bitset_merge_operator.i: c_src/bitset_merge_operator.cc.i

.PHONY : c_src/bitset_merge_operator.i

# target to preprocess a source file
c_src/bitset_merge_operator.cc.i:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/bitset_merge_operator.cc.i
.PHONY : c_src/bitset_merge_operator.cc.i

c_src/bitset_merge_operator.s: c_src/bitset_merge_operator.cc.s

.PHONY : c_src/bitset_merge_operator.s

# target to generate assembly for a file
c_src/bitset_merge_operator.cc.s:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/bitset_merge_operator.cc.s
.PHONY : c_src/bitset_merge_operator.cc.s

c_src/cache.o: c_src/cache.cc.o

.PHONY : c_src/cache.o

# target to build an object file
c_src/cache.cc.o:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/cache.cc.o
.PHONY : c_src/cache.cc.o

c_src/cache.i: c_src/cache.cc.i

.PHONY : c_src/cache.i

# target to preprocess a source file
c_src/cache.cc.i:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/cache.cc.i
.PHONY : c_src/cache.cc.i

c_src/cache.s: c_src/cache.cc.s

.PHONY : c_src/cache.s

# target to generate assembly for a file
c_src/cache.cc.s:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/cache.cc.s
.PHONY : c_src/cache.cc.s

c_src/counter_merge_operator.o: c_src/counter_merge_operator.cc.o

.PHONY : c_src/counter_merge_operator.o

# target to build an object file
c_src/counter_merge_operator.cc.o:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/counter_merge_operator.cc.o
.PHONY : c_src/counter_merge_operator.cc.o

c_src/counter_merge_operator.i: c_src/counter_merge_operator.cc.i

.PHONY : c_src/counter_merge_operator.i

# target to preprocess a source file
c_src/counter_merge_operator.cc.i:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/counter_merge_operator.cc.i
.PHONY : c_src/counter_merge_operator.cc.i

c_src/counter_merge_operator.s: c_src/counter_merge_operator.cc.s

.PHONY : c_src/counter_merge_operator.s

# target to generate assembly for a file
c_src/counter_merge_operator.cc.s:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/counter_merge_operator.cc.s
.PHONY : c_src/counter_merge_operator.cc.s

c_src/env.o: c_src/env.cc.o

.PHONY : c_src/env.o

# target to build an object file
c_src/env.cc.o:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/env.cc.o
.PHONY : c_src/env.cc.o

c_src/env.i: c_src/env.cc.i

.PHONY : c_src/env.i

# target to preprocess a source file
c_src/env.cc.i:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/env.cc.i
.PHONY : c_src/env.cc.i

c_src/env.s: c_src/env.cc.s

.PHONY : c_src/env.s

# target to generate assembly for a file
c_src/env.cc.s:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/env.cc.s
.PHONY : c_src/env.cc.s

c_src/erlang_merge.o: c_src/erlang_merge.cc.o

.PHONY : c_src/erlang_merge.o

# target to build an object file
c_src/erlang_merge.cc.o:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/erlang_merge.cc.o
.PHONY : c_src/erlang_merge.cc.o

c_src/erlang_merge.i: c_src/erlang_merge.cc.i

.PHONY : c_src/erlang_merge.i

# target to preprocess a source file
c_src/erlang_merge.cc.i:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/erlang_merge.cc.i
.PHONY : c_src/erlang_merge.cc.i

c_src/erlang_merge.s: c_src/erlang_merge.cc.s

.PHONY : c_src/erlang_merge.s

# target to generate assembly for a file
c_src/erlang_merge.cc.s:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/erlang_merge.cc.s
.PHONY : c_src/erlang_merge.cc.s

c_src/erocksdb.o: c_src/erocksdb.cc.o

.PHONY : c_src/erocksdb.o

# target to build an object file
c_src/erocksdb.cc.o:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/erocksdb.cc.o
.PHONY : c_src/erocksdb.cc.o

c_src/erocksdb.i: c_src/erocksdb.cc.i

.PHONY : c_src/erocksdb.i

# target to preprocess a source file
c_src/erocksdb.cc.i:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/erocksdb.cc.i
.PHONY : c_src/erocksdb.cc.i

c_src/erocksdb.s: c_src/erocksdb.cc.s

.PHONY : c_src/erocksdb.s

# target to generate assembly for a file
c_src/erocksdb.cc.s:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/erocksdb.cc.s
.PHONY : c_src/erocksdb.cc.s

c_src/erocksdb_column_family.o: c_src/erocksdb_column_family.cc.o

.PHONY : c_src/erocksdb_column_family.o

# target to build an object file
c_src/erocksdb_column_family.cc.o:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/erocksdb_column_family.cc.o
.PHONY : c_src/erocksdb_column_family.cc.o

c_src/erocksdb_column_family.i: c_src/erocksdb_column_family.cc.i

.PHONY : c_src/erocksdb_column_family.i

# target to preprocess a source file
c_src/erocksdb_column_family.cc.i:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/erocksdb_column_family.cc.i
.PHONY : c_src/erocksdb_column_family.cc.i

c_src/erocksdb_column_family.s: c_src/erocksdb_column_family.cc.s

.PHONY : c_src/erocksdb_column_family.s

# target to generate assembly for a file
c_src/erocksdb_column_family.cc.s:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/erocksdb_column_family.cc.s
.PHONY : c_src/erocksdb_column_family.cc.s

c_src/erocksdb_db.o: c_src/erocksdb_db.cc.o

.PHONY : c_src/erocksdb_db.o

# target to build an object file
c_src/erocksdb_db.cc.o:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/erocksdb_db.cc.o
.PHONY : c_src/erocksdb_db.cc.o

c_src/erocksdb_db.i: c_src/erocksdb_db.cc.i

.PHONY : c_src/erocksdb_db.i

# target to preprocess a source file
c_src/erocksdb_db.cc.i:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/erocksdb_db.cc.i
.PHONY : c_src/erocksdb_db.cc.i

c_src/erocksdb_db.s: c_src/erocksdb_db.cc.s

.PHONY : c_src/erocksdb_db.s

# target to generate assembly for a file
c_src/erocksdb_db.cc.s:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/erocksdb_db.cc.s
.PHONY : c_src/erocksdb_db.cc.s

c_src/erocksdb_iter.o: c_src/erocksdb_iter.cc.o

.PHONY : c_src/erocksdb_iter.o

# target to build an object file
c_src/erocksdb_iter.cc.o:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/erocksdb_iter.cc.o
.PHONY : c_src/erocksdb_iter.cc.o

c_src/erocksdb_iter.i: c_src/erocksdb_iter.cc.i

.PHONY : c_src/erocksdb_iter.i

# target to preprocess a source file
c_src/erocksdb_iter.cc.i:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/erocksdb_iter.cc.i
.PHONY : c_src/erocksdb_iter.cc.i

c_src/erocksdb_iter.s: c_src/erocksdb_iter.cc.s

.PHONY : c_src/erocksdb_iter.s

# target to generate assembly for a file
c_src/erocksdb_iter.cc.s:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/erocksdb_iter.cc.s
.PHONY : c_src/erocksdb_iter.cc.s

c_src/erocksdb_snapshot.o: c_src/erocksdb_snapshot.cc.o

.PHONY : c_src/erocksdb_snapshot.o

# target to build an object file
c_src/erocksdb_snapshot.cc.o:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/erocksdb_snapshot.cc.o
.PHONY : c_src/erocksdb_snapshot.cc.o

c_src/erocksdb_snapshot.i: c_src/erocksdb_snapshot.cc.i

.PHONY : c_src/erocksdb_snapshot.i

# target to preprocess a source file
c_src/erocksdb_snapshot.cc.i:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/erocksdb_snapshot.cc.i
.PHONY : c_src/erocksdb_snapshot.cc.i

c_src/erocksdb_snapshot.s: c_src/erocksdb_snapshot.cc.s

.PHONY : c_src/erocksdb_snapshot.s

# target to generate assembly for a file
c_src/erocksdb_snapshot.cc.s:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/erocksdb_snapshot.cc.s
.PHONY : c_src/erocksdb_snapshot.cc.s

c_src/rate_limiter.o: c_src/rate_limiter.cc.o

.PHONY : c_src/rate_limiter.o

# target to build an object file
c_src/rate_limiter.cc.o:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/rate_limiter.cc.o
.PHONY : c_src/rate_limiter.cc.o

c_src/rate_limiter.i: c_src/rate_limiter.cc.i

.PHONY : c_src/rate_limiter.i

# target to preprocess a source file
c_src/rate_limiter.cc.i:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/rate_limiter.cc.i
.PHONY : c_src/rate_limiter.cc.i

c_src/rate_limiter.s: c_src/rate_limiter.cc.s

.PHONY : c_src/rate_limiter.s

# target to generate assembly for a file
c_src/rate_limiter.cc.s:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/rate_limiter.cc.s
.PHONY : c_src/rate_limiter.cc.s

c_src/refobjects.o: c_src/refobjects.cc.o

.PHONY : c_src/refobjects.o

# target to build an object file
c_src/refobjects.cc.o:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/refobjects.cc.o
.PHONY : c_src/refobjects.cc.o

c_src/refobjects.i: c_src/refobjects.cc.i

.PHONY : c_src/refobjects.i

# target to preprocess a source file
c_src/refobjects.cc.i:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/refobjects.cc.i
.PHONY : c_src/refobjects.cc.i

c_src/refobjects.s: c_src/refobjects.cc.s

.PHONY : c_src/refobjects.s

# target to generate assembly for a file
c_src/refobjects.cc.s:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/refobjects.cc.s
.PHONY : c_src/refobjects.cc.s

c_src/transactions.o: c_src/transactions.cc.o

.PHONY : c_src/transactions.o

# target to build an object file
c_src/transactions.cc.o:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/transactions.cc.o
.PHONY : c_src/transactions.cc.o

c_src/transactions.i: c_src/transactions.cc.i

.PHONY : c_src/transactions.i

# target to preprocess a source file
c_src/transactions.cc.i:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/transactions.cc.i
.PHONY : c_src/transactions.cc.i

c_src/transactions.s: c_src/transactions.cc.s

.PHONY : c_src/transactions.s

# target to generate assembly for a file
c_src/transactions.cc.s:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/transactions.cc.s
.PHONY : c_src/transactions.cc.s

c_src/util.o: c_src/util.cc.o

.PHONY : c_src/util.o

# target to build an object file
c_src/util.cc.o:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/util.cc.o
.PHONY : c_src/util.cc.o

c_src/util.i: c_src/util.cc.i

.PHONY : c_src/util.i

# target to preprocess a source file
c_src/util.cc.i:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/util.cc.i
.PHONY : c_src/util.cc.i

c_src/util.s: c_src/util.cc.s

.PHONY : c_src/util.s

# target to generate assembly for a file
c_src/util.cc.s:
	$(MAKE) -f CMakeFiles/rocksdb.so.dir/build.make CMakeFiles/rocksdb.so.dir/c_src/util.cc.s
.PHONY : c_src/util.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rocksdb.so"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... rocksdb"
	@echo "... c_src/backup.o"
	@echo "... c_src/backup.i"
	@echo "... c_src/backup.s"
	@echo "... c_src/batch.o"
	@echo "... c_src/batch.i"
	@echo "... c_src/batch.s"
	@echo "... c_src/bitset_merge_operator.o"
	@echo "... c_src/bitset_merge_operator.i"
	@echo "... c_src/bitset_merge_operator.s"
	@echo "... c_src/cache.o"
	@echo "... c_src/cache.i"
	@echo "... c_src/cache.s"
	@echo "... c_src/counter_merge_operator.o"
	@echo "... c_src/counter_merge_operator.i"
	@echo "... c_src/counter_merge_operator.s"
	@echo "... c_src/env.o"
	@echo "... c_src/env.i"
	@echo "... c_src/env.s"
	@echo "... c_src/erlang_merge.o"
	@echo "... c_src/erlang_merge.i"
	@echo "... c_src/erlang_merge.s"
	@echo "... c_src/erocksdb.o"
	@echo "... c_src/erocksdb.i"
	@echo "... c_src/erocksdb.s"
	@echo "... c_src/erocksdb_column_family.o"
	@echo "... c_src/erocksdb_column_family.i"
	@echo "... c_src/erocksdb_column_family.s"
	@echo "... c_src/erocksdb_db.o"
	@echo "... c_src/erocksdb_db.i"
	@echo "... c_src/erocksdb_db.s"
	@echo "... c_src/erocksdb_iter.o"
	@echo "... c_src/erocksdb_iter.i"
	@echo "... c_src/erocksdb_iter.s"
	@echo "... c_src/erocksdb_snapshot.o"
	@echo "... c_src/erocksdb_snapshot.i"
	@echo "... c_src/erocksdb_snapshot.s"
	@echo "... c_src/rate_limiter.o"
	@echo "... c_src/rate_limiter.i"
	@echo "... c_src/rate_limiter.s"
	@echo "... c_src/refobjects.o"
	@echo "... c_src/refobjects.i"
	@echo "... c_src/refobjects.s"
	@echo "... c_src/transactions.o"
	@echo "... c_src/transactions.i"
	@echo "... c_src/transactions.s"
	@echo "... c_src/util.o"
	@echo "... c_src/util.i"
	@echo "... c_src/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

